name: direct_hiring
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  http: ^1.2.2
  google_fonts: ^6.2.1
  get: ^4.6.5
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  get_storage: ^2.1.1
  connectivity_plus: ^4.0.1
  intl: ^0.19.0
  lottie: ^3.1.3
  socket_io_client: ^3.0.0
  file_picker: ^8.1.7
  timelines: ^0.1.0
  table_calendar: ^3.1.3
  video_player: ^2.9.5
  url_launcher: ^6.3.1
  curved_navigation_bar: ^1.0.6
  motion_tab_bar: ^2.0.4
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  dotted_border: ^3.1.0
  flutter_intl_phone_field: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgImages/
    - assets/videos/video.mp4
